databases:
  - name: bot-db
    databaseName: saas_bot
    plan: free
    ipAllowList: ["0.0.0.0/0"]
    extensions: [pgvector]

services:
  - type: redis
    name: bot-cache
    plan: free

  - type: web
    name: saas-expert-bot
    runtime: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python saas-expert-bot.py"
    envVars:
      fromGroup: bot-env     # создадим в Render
