databases:
  - name: bot-db
    databaseName: saas_bot
    plan: free
    ipAllowList: []          # обязательное поле

services:
  - type: redis
    name: bot-cache
    plan: free
    ipAllowList: []          # тоже обязательно

  - type: web
    name: saas-expert-bot
    runtime: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python saas-expert-bot.py
    envVars:
      - fromGroup: bot-env   # дефис сохраняем!
