databases:
  - name: bot-db
    databaseName: saas_bot
    plan: free               # enough for MVP
    # ipAllowList оставляем пустым — внутренние сервисы и так имеют доступ
    # pgvector подключим SQL-командой после создания базы

services:
  - type: redis
    name: bot-cache
    plan: free

  - type: web
    name: saas-expert-bot
    runtime: python
    region: frankfurt        # или ближайший
    buildCommand: pip install -r requirements.txt
    startCommand: python saas-expert-bot.py
    envVars:
      - fromGroup: bot-env   # 👈 обязательный дефис! массив EnvVars
